### ISSUE TITLE
Which permissions to create the GitHub token with

### ISSUE THREAD

**Issue by gotjosh** [tj/triage#12]
## Prerequisites

* [x] I searched to see if the issue already exists.

## Description

I can't decide which permissions to use when creating the GitHub Token. I ended up just giving it access to notifications and that seemed to work but I'm assuming it would probably fail when trying to create a comment on an issue.

Would be good to document what which permissions does triage need and what are they for.

**Comment by tj** [comment]
Good call, I'll double check the minimum requirements and document those, mine is a bit more open.
